"""Phase 1, step 1: raw xlsx -> cleaned hourly parquet + data-cleaning report.

Usage::

    python scripts/01_prepare_data.py --config config.yaml

Outputs:

* ``data/processed/all_stations.parquet``        -- combined cleaned hourly data
* ``data/processed/stations/<station>.parquet``  -- one file per station
* ``outputs/data_cleaning_report.md``            -- full accounting

After this script, nothing in the project reads the raw xlsx again.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data.clean import CleanReport, clean
from src.data.load import LoadReport, load_all
from src.utils import load_config, seed_everything, setup_logging


def write_cleaning_report(
    path: Path,
    df: pd.DataFrame,
    load_rep: LoadReport,
    clean_rep: CleanReport,
    cfg: dict,
) -> None:
    """Render the markdown data-cleaning report from the two report objects."""
    meas = cfg["data"]["measurement_cols"]
    lines: list[str] = ["# Data Cleaning Report", ""]
    lines.append(f"Generated by `scripts/01_prepare_data.py` (seed={cfg['seed']}).")
    lines.append("")

    lines.append("## 1. Loading (per raw file)")
    lines.append("")
    lines.append("| Year | Rows in | Unit rows stripped | Non-unit NaT rows dropped | Rows out |")
    lines.append("|---|---|---|---|---|")
    for y in sorted(load_rep.rows_in):
        lines.append(
            f"| {y} | {load_rep.rows_in[y]:,} | {load_rep.unit_rows[y]} | "
            f"{load_rep.nat_rows_non_unit[y]} | {load_rep.rows_out[y]:,} |"
        )
    lines.append("")
    lines.append(
        "Each raw file concatenates per-station blocks, each beginning with its own "
        "unit row (`ppb`, `ug/m3`, ...); all such rows were detected by regex over "
        "every measurement column and stripped. Columns were aligned strictly by "
        "name (the 2024 file has PM2.5/PM10 in swapped positional order)."
    )
    lines.append("")

    if any(load_rep.dropped_cols.values()):
        lines.append("### Dropped columns")
        lines.append("")
        for y, cols in load_rep.dropped_cols.items():
            for col, n in cols.items():
                lines.append(
                    f"- {y}: `{col}` dropped ({n:,} non-null values out of "
                    f"{load_rep.rows_in[y]:,} rows)."
                )
        lines.append("")

    if load_rep.station_renames:
        lines.append("### Station name normalization")
        lines.append("")
        for old, new in sorted(load_rep.station_renames.items()):
            lines.append(f"- `{old}` -> `{new}`")
        lines.append("")

    lines.append("### Numeric coercion failures (values lost per column)")
    lines.append("")
    years = sorted(load_rep.coercion_failures)
    lines.append("| Column | " + " | ".join(str(y) for y in years) + " |")
    lines.append("|---|" + "---|" * len(years))
    for col in meas:
        vals = [load_rep.coercion_failures[y].get(col, 0) for y in years]
        lines.append(f"| {col} | " + " | ".join(str(v) for v in vals) + " |")
    lines.append("")

    lines.append("## 2. Cleaning rules (flag-and-NaN; rows are never dropped)")
    lines.append("")
    lines.append(f"- Duplicated (station, timestamp) rows dropped: **{clean_rep.duplicates_dropped}**")
    lines.append("")
    sentinels = cfg["clean"].get("sentinel_values", {})
    if sentinels:
        lines.append("### Instrument error/saturation codes (exact-match flag-and-NaN)")
        lines.append("")
        lines.append("| Column | Codes | Values flagged → NaN |")
        lines.append("|---|---|---|")
        for col, codes in sentinels.items():
            n = clean_rep.sentinel_flagged.get(col, 0)
            lines.append(f"| {col} | {codes} | {n:,} |")
        lines.append("")
        lines.append(
            "Rationale: these values repeat verbatim hundreds of times at the "
            "instrument ceiling (e.g. 985.0 appears 1,328× in 2024 PM2.5, "
            "including monsoon months where such concentrations are physically "
            "impossible) — error codes, not measurements."
        )
        lines.append("")
    lines.append("### Plausibility bounds")
    lines.append("")
    lines.append("| Column | Bounds | Values flagged → NaN |")
    lines.append("|---|---|---|")
    for col, (lo, hi) in cfg["clean"]["bounds"].items():
        n = clean_rep.bounds_flagged.get(col, 0)
        lines.append(f"| {col} | [{lo}, {hi}] | {n:,} |")
    lines.append("")
    lines.append(
        f"### Stuck-sensor runs (≥ {cfg['clean']['stuck_run_length']} identical "
        "consecutive non-zero values)"
    )
    lines.append("")
    lines.append("| Column | Values flagged → NaN |")
    lines.append("|---|---|")
    for col in meas:
        lines.append(f"| {col} | {clean_rep.stuck_flagged.get(col, 0):,} |")
    lines.append("")

    lines.append("## 3. Hourly reindexing")
    lines.append("")
    lines.append(
        f"Rows before reindex: **{clean_rep.rows_before_reindex:,}**, after: "
        f"**{clean_rep.rows_after_reindex:,}** "
        f"({clean_rep.rows_after_reindex - clean_rep.rows_before_reindex:,} explicit "
        "gap rows inserted). Each station was reindexed to its full hourly range:"
    )
    lines.append("")
    lines.append("| Station | First hour | Last hour | Rows | PM2.5 missing % |")
    lines.append("|---|---|---|---|---|")
    for st in sorted(clean_rep.station_ranges):
        lo, hi = clean_rep.station_ranges[st]
        sub = df[df["station"] == st]
        miss = sub["PM2.5"].isna().mean() * 100
        lines.append(f"| {st} | {lo} | {hi} | {len(sub):,} | {miss:.1f} |")
    lines.append("")

    lines.append("## 4. Final missingness per variable (after cleaning + reindex)")
    lines.append("")
    lines.append("| Column | Missing % |")
    lines.append("|---|---|")
    for col in meas:
        lines.append(f"| {col} | {df[col].isna().mean() * 100:.1f} |")
    lines.append("")
    excl = cfg["data"].get("exclude_features", [])
    if excl:
        lines.append(
            f"Columns excluded from modeling due to extreme missingness: "
            f"{', '.join(f'`{c}`' for c in excl)} (values retained in parquet)."
        )
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=None, help="path to config.yaml")
    args = parser.parse_args()

    cfg = load_config(args.config)
    logger = setup_logging("01_prepare_data", cfg["paths"]["logs_dir"])
    seed_everything(cfg["seed"], cfg.get("num_threads"))

    df, load_rep = load_all(cfg)
    df, clean_rep = clean(df, cfg)

    processed = Path(cfg["paths"]["processed_dir"])
    combined_path = processed / "all_stations.parquet"
    df.to_parquet(combined_path, index=False)
    logger.info("wrote %s (%d rows)", combined_path, len(df))

    station_dir = processed / "stations"
    station_dir.mkdir(exist_ok=True)
    for st, grp in df.groupby("station"):
        p = station_dir / f"{st.replace(' ', '_')}.parquet"
        grp.reset_index(drop=True).to_parquet(p, index=False)
    logger.info("wrote %d per-station parquet files to %s", df["station"].nunique(), station_dir)

    report_path = Path(cfg["paths"]["outputs_dir"]) / "data_cleaning_report.md"
    write_cleaning_report(report_path, df, load_rep, clean_rep, cfg)
    logger.info("wrote cleaning report to %s", report_path)


if __name__ == "__main__":
    main()
